CREATE DATABASE IF NOT EXISTS ANKIU;
USE ANKIU;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
  ID CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;